server:
  port: 666
spring:
  datasource:
    dbcp2:
      initial-size: 5
      max-idle: 10
      max-wait-millis: 10000
      min-idle: 5
      test-on-borrow: false
      test-while-idle: true
      time-between-eviction-runs-millis: 18800
      validation-query: SELECT 1
    driver-class-name: com.mysql.jdbc.Driver
    type: org.apache.commons.dbcp2.BasicDataSource
    url: jdbc:mysql://127.0.0.1:3306/learn?useUnicode=true&characterEncoding=UTF-8&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8
    username: root
    password: 123456
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  redis:
    host: localhost
    database: 1
    port: 6379
    timeout: 3600
    password:
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1
        min-idle: 0
      shutdown-timeout: 0
  thymeleaf:
    prefix: classpath:/templates/
    cache: false
    suffix: .html
    mode: HTML5
    encoding: utf-8
    servlet:
      content-type: text/html
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
  mvc:
    static-path-pattern: /**

logging:
  config: classpath:logback.xml


cache:
  type: redis
